// GlobalStateContext.js
import React, { useState } from "react";
import GlobalStateContext from "./GlobalStateContext";
import { effect, useColorMode } from "@chakra-ui/react";
import { v4 as uuidv4 } from "uuid";

const getRandomDate = (start, end) => {
  const date = new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  );
  return date.toISOString();
};

const startDate = new Date(2020, 0, 1); // January 1, 2020
const endDate = new Date(); // Current date

const GlobalStateProvider = ({ children }) => {
  const [isAuthenticate, setIsAuthenticate] = useState(false);
  const [memberIfo, setMemberInfo] = useState();
  const [communityMembers, setCommityMembers] = useState();
  const [slideFromRight, setSlideFormRight] = useState(false);

  const { colorMode, toggleColorMode } = useColorMode();
  const [sponser, setSponser] = useState([
    {
      id: 1,
      sponserName: "John Doe",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "1234567890",
      sponserAddress: "123 Main St, Springfield, USA",
      accountHolderName: "John Doe",
      bankName: "Example Bank",
      accountNumber: "1234567890",
      bankBranch: "Main Branch",
      branchAddress: "456 Elm St, Springfield, USA",
      ifscCode: "IFSC12345",
      swiftCode: "SWIFT56789",
      routingNumber: "987654321",
      iban: "IBAN987654321",
      accountType: "savings",
      bankPhoneNumber: "9876543210",
      bankEmail: "john.doe@example.com",
      status: true,
      createdAt: "45",
    },
    {
      id: 2,
      sponserName: "Jane Smith",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "9876543210",
      sponserAddress: "456 Oak St, Metropolis, USA",
      accountHolderName: "Jane Smith",
      bankName: "Another Bank",
      accountNumber: "0987654321",
      bankBranch: "Downtown Branch",
      branchAddress: "789 Pine St, Metropolis, USA",
      ifscCode: "IFSC54321",
      swiftCode: "SWIFT98765",
      routingNumber: "123456789",
      iban: "IBAN123456789",
      accountType: "checking",
      bankPhoneNumber: "1234567890",
      bankEmail: "jane.smith@example.com",
      status: false,
      createdAt: "45",
    },
    {
      id: 3,
      sponserName: "Alice Johnson",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "1231231234",
      sponserAddress: "789 Pine St, Gotham, USA",
      accountHolderName: "Alice Johnson",
      bankName: "Gotham Bank",
      accountNumber: "5678901234",
      bankBranch: "Uptown Branch",
      branchAddress: "101 Oak St, Gotham, USA",
      ifscCode: "IFSC67890",
      swiftCode: "SWIFT34567",
      routingNumber: "987654321",
      iban: "IBAN345678901",
      accountType: "business",
      bankPhoneNumber: "5556667777",
      bankEmail: "alice.johnson@example.com",
      status: true,
      createdAt: "12",
    },
    {
      id: 4,
      sponserName: "Bob Brown",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "3213214321",
      sponserAddress: "101 Maple St, Smallville, USA",
      accountHolderName: "Bob Brown",
      bankName: "Smallville Credit Union",
      accountNumber: "5432109876",
      bankBranch: "Main Street Branch",
      branchAddress: "202 Pine St, Smallville, USA",
      ifscCode: "IFSC43210",
      swiftCode: "SWIFT87654",
      routingNumber: "123456789",
      iban: "IBAN567890123",
      accountType: "savings",
      bankPhoneNumber: "8889990000",
      bankEmail: "bob.brown@example.com",
      status: true,
      createdAt: "7",
    },
    {
      id: 5,
      sponserName: "Charlie Davis",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "5555555555",
      sponserAddress: "202 Birch St, Star City, USA",
      accountHolderName: "Charlie Davis",
      bankName: "Star City Bank",
      accountNumber: "9876543210",
      bankBranch: "Downtown Branch",
      branchAddress: "303 Oak St, Star City, USA",
      ifscCode: "IFSC55555",
      swiftCode: "SWIFT00000",
      routingNumber: "111223344",
      iban: "IBAN999988887",
      accountType: "checking",
      bankPhoneNumber: "1112223333",
      bankEmail: "charlie.davis@example.com",
      status: false,
      createdAt: "4",
    },
    {
      id: 6,
      sponserName: "Daniel Evans",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "4444444444",
      sponserAddress: "303 Cedar St, Central City, USA",
      accountHolderName: "Daniel Evans",
      bankName: "Central City Bank",
      accountNumber: "4444555566",
      bankBranch: "Uptown Branch",
      branchAddress: "404 Elm St, Central City, USA",
      ifscCode: "IFSC44444",
      swiftCode: "SWIFT11111",
      routingNumber: "555666777",
      iban: "IBAN4444555566",
      accountType: "business",
      bankPhoneNumber: "4445556666",
      bankEmail: "daniel.evans@example.com",
      status: true,
      createdAt: "2",
    },
    {
      id: 7,
      sponserName: "Ella Fitzgerald",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "3333333333",
      sponserAddress: "404 Elm St, Coast City, USA",
      accountHolderName: "Ella Fitzgerald",
      bankName: "Coast City Bank",
      accountNumber: "3333444455",
      bankBranch: "Downtown Branch",
      branchAddress: "505 Cedar St, Coast City, USA",
      ifscCode: "IFSC77777",
      swiftCode: "SWIFT22222",
      routingNumber: "888999000",
      iban: "IBAN888999000",
      accountType: "savings",
      bankPhoneNumber: "7778889999",
      bankEmail: "ella.fitzgerald@example.com",
      status: false,
      createdAt: "9",
    },
    {
      id: 8,
      sponserName: "Frank Green",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "2222222222",
      sponserAddress: "505 Ash St, Keystone City, USA",
      accountHolderName: "Frank Green",
      bankName: "Keystone City Bank",
      accountNumber: "2222333344",
      bankBranch: "Main Branch",
      branchAddress: "606 Birch St, Keystone City, USA",
      ifscCode: "IFSC88888",
      swiftCode: "SWIFT33333",
      routingNumber: "444555666",
      iban: "IBAN444555666",
      accountType: "checking",
      bankPhoneNumber: "2222333444",
      bankEmail: "frank.green@example.com",
      status: true,
      createdAt: "8",
    },
    {
      id: 9,
      sponserName: "Grace Hall",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "1111111111",
      sponserAddress: "606 Willow St, Hub City, USA",
      accountHolderName: "Grace Hall",
      bankName: "Hub City Bank",
      accountNumber: "1111222233",
      bankBranch: "Downtown Branch",
      branchAddress: "707 Cedar St, Hub City, USA",
      ifscCode: "IFSC99999",
      swiftCode: "SWIFT44444",
      routingNumber: "555566677",
      iban: "IBAN555566677",
      accountType: "business",
      bankPhoneNumber: "1111222333",
      bankEmail: "grace.hall@example.com",
      status: true,
      createdAt: "1",
    },
    {
      id: 10,
      sponserName: "Henry Ingram",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "6666666666",
      sponserAddress: "707 Spruce St, Fawcett City, USA",
      accountHolderName: "Henry Ingram",
      bankName: "Fawcett City Bank",
      accountNumber: "6666777788",
      bankBranch: "Main Street Branch",
      branchAddress: "808 Oak St, Fawcett City, USA",
      ifscCode: "IFSC66666",
      swiftCode: "SWIFT55555",
      routingNumber: "999000111",
      iban: "IBAN999000111",
      accountType: "savings",
      bankPhoneNumber: "6666777888",
      bankEmail: "henry.ingram@example.com",
      status: false,
      createdAt: "6",
    },
    {
      id: 11,
      sponserName: "Grace Hall",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "1111111111",
      sponserAddress: "606 Willow St, Hub City, USA",
      accountHolderName: "Grace Hall",
      bankName: "Hub City Bank",
      accountNumber: "1111222233",
      bankBranch: "Downtown Branch",
      branchAddress: "707 Cedar St, Hub City, USA",
      ifscCode: "IFSC99999",
      swiftCode: "SWIFT44444",
      routingNumber: "555566677",
      iban: "IBAN555566677",
      accountType: "business",
      bankPhoneNumber: "1111222333",
      bankEmail: "grace.hall@example.com",
      status: true,
      createdAt: "1",
    },
    {
      id: 12,
      sponserName: "Henry Ingram",
      sponserNameArabic:"الرجاء إدخال القيمة",
      mobileNo: "6666666666",
      sponserAddress: "707 Spruce St, Fawcett City, USA",
      accountHolderName: "Henry Ingram",
      bankName: "Fawcett City Bank",
      accountNumber: "6666777788",
      bankBranch: "Main Street Branch",
      branchAddress: "808 Oak St, Fawcett City, USA",
      ifscCode: "IFSC66666",
      swiftCode: "SWIFT55555",
      routingNumber: "999000111",
      iban: "IBAN999000111",
      accountType: "savings",
      bankPhoneNumber: "6666777888",
      bankEmail: "henry.ingram@example.com",
      status: false,
      createdAt: "6",
    },
  ]);
  
  const [investmentType, setInvestmentType] = useState([
    {
      id: 1,
      investmentName: "Michael Scott",
      mobileNo: "0987654321",
      investmentAddress: "1725 Slough Ave, Scranton, USA",
      accountHolderName: "Michael Scott",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "1111222233",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC11111",
      swiftCode: "SWIFT12345",
      routingNumber: "123450987",
      iban: "IBAN1111222233",
      accountType: "checking",
      bankPhoneNumber: "0987654321",
      bankEmail: "michael.scott@example.com",
      status: true,
      createdAt: "45",
    },
    {
      id: 2,
      investmentName: "Pam Beesly",
      mobileNo: "1234509876",
      investmentAddress: "3487 Palm St, Scranton, USA",
      accountHolderName: "Pam Beesly",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "4444555566",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC44444",
      swiftCode: "SWIFT54321",
      routingNumber: "543211234",
      iban: "IBAN4444555566",
      accountType: "savings",
      bankPhoneNumber: "1234509876",
      bankEmail: "pam.beesly@example.com",
      status: false,
      createdAt: "45",
    },
    {
      id: 3,
      investmentName: "Jim Halpert",
      mobileNo: "2345678901",
      investmentAddress: "5701 Maple Ave, Scranton, USA",
      accountHolderName: "Jim Halpert",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "7777888899",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC77777",
      swiftCode: "SWIFT87654",
      routingNumber: "987654321",
      iban: "IBAN7777888899",
      accountType: "business",
      bankPhoneNumber: "2345678901",
      bankEmail: "jim.halpert@example.com",
      status: true,
      createdAt: "12",
    },
    {
      id: 4,
      investmentName: "Dwight Schrute",
      mobileNo: "3456789012",
      investmentAddress: "1725 Slough Ave, Scranton, USA",
      accountHolderName: "Dwight Schrute",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "3333444455",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC33333",
      swiftCode: "SWIFT34567",
      routingNumber: "765432109",
      iban: "IBAN3333444455",
      accountType: "savings",
      bankPhoneNumber: "3456789012",
      bankEmail: "dwight.schrute@example.com",
      status: true,
      createdAt: "7",
    },
    {
      id: 5,
      investmentName: "Stanley Hudson",
      mobileNo: "4567890123",
      investmentAddress: "202 Industrial St, Scranton, USA",
      accountHolderName: "Stanley Hudson",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "5555666677",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC55555",
      swiftCode: "SWIFT45678",
      routingNumber: "876543210",
      iban: "IBAN5555666677",
      accountType: "checking",
      bankPhoneNumber: "4567890123",
      bankEmail: "stanley.hudson@example.com",
      status: false,
      createdAt: "4",
    },
    {
      id: 6,
      investmentName: "Angela Martin",
      mobileNo: "5678901234",
      investmentAddress: "7777 Cat Ave, Scranton, USA",
      accountHolderName: "Angela Martin",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "8888999900",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC88888",
      swiftCode: "SWIFT56789",
      routingNumber: "987654321",
      iban: "IBAN8888999900",
      accountType: "business",
      bankPhoneNumber: "5678901234",
      bankEmail: "angela.martin@example.com",
      status: true,
      createdAt: "2",
    },
    {
      id: 7,
      investmentName: "Kevin Malone",
      mobileNo: "6789012345",
      investmentAddress: "3333 Cookie Ln, Scranton, USA",
      accountHolderName: "Kevin Malone",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "9999000011",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC99999",
      swiftCode: "SWIFT67890",
      routingNumber: "876543210",
      iban: "IBAN9999000011",
      accountType: "savings",
      bankPhoneNumber: "6789012345",
      bankEmail: "kevin.malone@example.com",
      status: false,
      createdAt: "9",
    },
    {
      id: 8,
      investmentName: "Phyllis Vance",
      mobileNo: "7890123456",
      investmentAddress: "4545 Knitting Way, Scranton, USA",
      accountHolderName: "Phyllis Vance",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "0000111122",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC00000",
      swiftCode: "SWIFT78901",
      routingNumber: "123456789",
      iban: "IBAN0000111122",
      accountType: "checking",
      bankPhoneNumber: "7890123456",
      bankEmail: "phyllis.vance@example.com",
      status: true,
      createdAt: "8",
    },
    {
      id: 9,
      investmentName: "Meredith Palmer",
      mobileNo: "8901234567",
      investmentAddress: "6666 Booze Blvd, Scranton, USA",
      accountHolderName: "Meredith Palmer",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "1111222233",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC11111",
      swiftCode: "SWIFT89012",
      routingNumber: "123450987",
      iban: "IBAN1111222233",
      accountType: "business",
      bankPhoneNumber: "8901234567",
      bankEmail: "meredith.palmer@example.com",
      status: true,
      createdAt: "1"
    },
    {
      id: 10,
      investmentName: "Ryan Howard",
      mobileNo: "9012345678",
      investmentAddress: "7777 Temp Way, Scranton, USA",
      accountHolderName: "Ryan Howard",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "2222333344",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC22222",
      swiftCode: "SWIFT90123",
      routingNumber: "234561098",
      iban: "IBAN2222333344",
      accountType: "savings",
      bankPhoneNumber: "9012345678",
      bankEmail: "ryan.howard@example.com",
      status: false,
      createdAt: "6",
    },
    {
      id: 11,
      investmentName: "Oscar Martinez",
      mobileNo: "0123456789",
      investmentAddress: "2222 Math St, Scranton, USA",
      accountHolderName: "Oscar Martinez",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "3333444455",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC33333",
      swiftCode: "SWIFT01234",
      routingNumber: "345671209",
      iban: "IBAN3333444455",
      accountType: "business",
      bankPhoneNumber: "0123456789",
      bankEmail: "oscar.martinez@example.com",
      status: true,
      createdAt: "1",
    },
    {
      id: 12,
      investmentName: "Kelly Kapoor",
      mobileNo: "9876543210",
      investmentAddress: "4444 Fashion Ave, Scranton, USA",
      accountHolderName: "Kelly Kapoor",
      bankName: "Dunder Mifflin Bank",
      accountNumber: "4444555566",
      bankBranch: "Scranton Branch",
      branchAddress: "101 Paper St, Scranton, USA",
      ifscCode: "IFSC44444",
      swiftCode: "SWIFT23456",
      routingNumber: "456781320",
      iban: "IBAN4444555566",
      accountType: "savings",
      bankPhoneNumber: "9876543210",
      bankEmail: "kelly.kapoor@example.com",
      status: false,
      createdAt: "6",
    },
  ]);
  

  const [investment, setInvestment] = useState([
    // {
    //   banner_image:
    //     "https://images.unsplash.com/photo-1667489022797-ab608913feeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw5fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
    //   ioName: "Multi Family Residence Portfolio",
    //   sponserName: "KKR",
    //   annualReturn: "12.5%",
    //   annualyield: "12.5%",
    //   minInvests: ",00 $0",
    //   targetClose: "24 December",
    //   year: "5-7 years",
    //   tenure: 92,
    //   quaterly: "Q2",
    //   destributedAmount: 62,
    //   ioName: "Sybil Christensen",
    //   ioNameArabic: "September Kelley",
    //   status: "Available"
    // },
    // {
    //   banner_image:
    //     "https://images.unsplash.com/photo-1667489022797-ab608913feeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw5fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
    //   ioName: "Multi Family Residence Portfolio",
    //   sponserName: "KKR",
    //   annualReturn: "12.5%",
    //   annualyield: "12.5%",
    //   minInvests: ",00 $0",
    //   targetClose: "24 December",
    //   year: "5-7 years",
    //   tenure: 92,
    //   quaterly: "Q2",
    //   destributedAmount: 62,
    //   ioName: "Sybil Christensen",
    //   ioNameArabic: "September Kelley",
    //   status: "Available"
    // },
    // {
    //   banner_image:
    //     "https://images.unsplash.com/photo-1667489022797-ab608913feeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw5fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
    //   ioName: "Multi Family Residence Portfolio",
    //   sponserName: "KKR",
    //   annualReturn: "12.5%",
    //   annualyield: "12.5%",
    //   minInvests: ",00 $0",
    //   targetClose: "24 December",
    //   year: "5-7 years",
    //   tenure: 92,
    //   quaterly: "Q2",
    //   destributedAmount: 62,
    //   ioName: "Sybil Christensen",
    //   ioNameArabic: "September Kelley",
    //   status: "Available"
    // },
  ]);

  const [rateExchange, setRateExchange] = useState([
    {
      id: uuidv4(),
      fromCurr: "USD $",
      toCurr: "BHD .د.ب;",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "USD $",
      toCurr: "KWD ·د.ك",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "USD $",
      toCurr: "OMR ﷼.",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "USD $",
      toCurr: "QAR ﷼.",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "USD $",
      toCurr: "SAR ﷼.",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "USD $",
      toCurr: "AED د.إ. ",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },

    {
      id: uuidv4(),
      fromCurr: "AED د.إ. ",
      toCurr: "USD $",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "SAR ﷼.",
      toCurr: "USD $",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "QAR ﷼.",
      toCurr: "USD $",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },

    {
      id: uuidv4(),
      fromCurr: "BHD .د.ب;",
      toCurr: "USD $",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "KWD ·د.ك",
      toCurr: "USD $",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
    {
      id: uuidv4(),
      fromCurr: "OMR ﷼.",
      toCurr: "USD $",
      effectFrom: getRandomDate(startDate, endDate),
      effectTill: getRandomDate(startDate, endDate),
      rate: 2.66,
    },
  ]);

  const [InvestorDetails, setInvestorDetails] = useState([
    {
      id: 1,
      InvestorName: "ICC",
      Sponsor: "Adani",
      InvestmentAmount: "1000000",
      Action: "Distribute",
    },
    {
      id: 2,
      InvestorName: "ECHO Investment",
      Sponsor: "Tata",
      InvestmentAmount: "2500000",
      Action: "Distribute",
    },
  ]);

  const [pendingRequest, setPendingRequest] = useState([
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
  ]);

  const [viewHistory, setViewHistory] = useState([
    {
      id: uuidv4(),
      date: "2024-01-15",
      Distribution: "Office supplies",
      charge: "200.50",
      year: "2024",
      quarter: "Q1",
      amount: 1500,
    },
    {
      id: uuidv4(),
      date: "2024-02-10",
      Distribution: "Marketing expenses",
      charge: "450.00",
      year: "2024",
      quarter: "Q1",
      amount: 2000,
    },
    {
      id: uuidv4(),
      date: "2024-03-05",
      Distribution: "Software subscription",
      charge: "300.75",
      year: "2024",
      quarter: "Q1",
      amount: 1200,
    },
    {
      id: uuidv4(),
      date: "2024-04-18",
      Distribution: "Travel expenses",
      charge: "600.30",
      year: "2024",
      quarter: "Q2",
      amount: 2500,
    },
    {
      id: uuidv4(),
      date: "2024-05-22",
      Distribution: "Consulting fees",
      charge: "800.00",
      year: "2024",
      quarter: "Q2",
      amount: 3000,
    },
    {
      id: uuidv4(),
      date: "2024-06-14",
      Distribution: "Office rent",
      charge: "1200.25",
      year: "2024",
      quarter: "Q2",
      amount: 3500,
    },
    {
      id: uuidv4(),
      date: "2024-07-09",
      Distribution: "Utilities",
      charge: "150.40",
      year: "2024",
      quarter: "Q3",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: "2024-08-29",
      Distribution: "Employee training",
      charge: "500.00",
      year: "2024",
      quarter: "Q3",
      amount: 1800,
    },
    {
      id: uuidv4(),
      date: "2024-09-13",
      Distribution: "Website maintenance",
      charge: "350.65",
      year: "2024",
      quarter: "Q3",
      amount: 1400,
    },
    {
      id: uuidv4(),
      date: "2024-10-23",
      Distribution: "Advertising",
      charge: "900.50",
      year: "2024",
      quarter: "Q4",
      amount: 2200,
    },
    {
      id: uuidv4(),
      date: "2024-10-23",
      Distribution: "Advertising",
      charge: "900.50",
      year: "2024",
      quarter: "Q4",
      amount: 2200,
    },
    {
      id: uuidv4(),
      date: "2024-10-23",
      Distribution: "Advertising",
      charge: "900.50",
      year: "2024",
      quarter: "Q4",
      amount: 2200,
    },
  ]);

  const [investorRequest, setInvestorRequest] = useState([
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
    {
      id: uuidv4(),
      date: getRandomDate(startDate, endDate),
      Distribution: "lorem ipsum dummy text",
      charge: "500",
      year: "2024",
      quater: "Q 1",
      amount: 1000,
    },
  ]);

  return (
    <GlobalStateContext.Provider
      value={{
        isAuthenticate,
        setIsAuthenticate,
        memberIfo,
        setMemberInfo,
        communityMembers,
        setCommityMembers,
        sponser,
        setSponser,
        colorMode,
        toggleColorMode,
        slideFromRight,
        setSlideFormRight,

        InvestorDetails,
        setInvestorDetails,
        investment,
        setInvestment,
        rateExchange,
        setRateExchange,
        pendingRequest,
        setPendingRequest,
        viewHistory,
        setViewHistory,
        investmentType,
        setInvestmentType,
        investorRequest,
        setInvestorRequest,
      }}
    >
      {children}
    </GlobalStateContext.Provider>
  );
};
export default GlobalStateProvider;
